### ISSUE TITLE
google categories 분류

### ISSUE THREAD

**Issue by TimidLion** [WhereToday/data#2]
google categories 분류
-    교통시설 : 데이터시각화할 때 레퍼런스로 삼기 위해 내버려두고
-    식사 / 쇼핑 / 유흥 카테고리 내에서 크게 세개
-    종교역사유적 시설을 별점으로 거르기
-    편의 시설은 제외하기. 큰 그림에 집중.

**Comment by ejklike** [comment]
front가 구현하는 대로 분류될 것
